import "./tasks/task-1.js";
import "./tasks/task-2.js";
import "./tasks/task-3.js";
import "./tasks/task-4.js";
import "./tasks/task-5.js";
import "./tasks/task-6.js";
import "./tasks/task-7.js";
import "./tasks/task-8.js";
import "./tasks/task-9.js";
